### ISSUE TITLE
Hidden inputs

### ISSUE THREAD

**Issue by sullof** [wdavidw/node-shell#17]
I am writing a password manager that runs in a shell. My basic problem using `shell` is that I cannot find a way to have an hidden input to allow the users to type their password in a secure way.
So, I wonder if this is supported but I haven't found it. If not, is there any plan of adding it?
Thanks so much,
F

**Comment by wdavidw** [comment]
I dont remember implementing anyting like it. As a matter of fact, node-shell isn't so much about asking questions to the user (at least i didnt implemented it) but more about recieving and routing commands.
